export const UPDATE_USERNAME = "UPDATE_USERNAME";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_CONFIRM_PASSWORD = "UPDATE_CONFIRM_PASSWORD";
export const UPDATE_EMAIL = "UPDATE_EMAIL";
export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_USERID = "UPDATE_USERID";
export const UPDATE_TOKEN_EXP = "UPDATE_TOKEN_EXP";
export const UPDATE_NAME = "UPDATE_NAME";
export const UPDATE_GENDER = "UPDATE_GENDER";
export const UPDATE_DOB = "UPDATE_DOB";
export const UPDATE_EXPERIENCE = "UPDATE_EXPERIENCE";
export const UPDATE_USER_TYPE = "UPDATE_USER_TYPE";

export const UPDATE_PROFILE_ID = "UPDATE_PROFILE_ID";
